# Generated by Django 3.1.4 on 2021-02-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('iframe_url', models.TextField()),
                ('url', models.TextField()),
                ('is_east_bay_route', models.BooleanField(default=False)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
